name: Check Project Health
run-name: Check if FastAPI runs successfully
on:
  push:
    branches:
      - main
jobs:
  Run-starter-script:
    runs-on: ubuntu-latest
    environment: demo-deployment-env
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create .env File
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "AUTH_SECRETE_KEY=${{ secrets.AUTH_SECRETE_KEY }}" >> .env
          echo "AUTH_ALGORITHM=${{ secrets.AUTH_ALGORITHM }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}" >> .env
          echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "ADMIN_DEFAULT_USERNAME=${{ secrets.ADMIN_DEFAULT_USERNAME }}" >> .env
          echo "ADMIN_DEFAULT_PASSWORD=${{ secrets.ADMIN_DEFAULT_PASSWORD }}" >> .env
          echo "ADMIN_DEFAULT_ROLE=${{ secrets.ADMIN_DEFAULT_ROLE}}" >> .env
          echo "ADMIN_DEFAULT_EMAIL=${{ secrets.ADMIN_DEFAULT_EMAIL }}" >> .env

      - name: Run Docker compose
        run: |
          docker compose up -d

      - name: Check containers
        run: |
          docker ps

      - name: Clean Up
        if: always()
        run: |
          docker system prune -a -f
